### ISSUE TITLE
Update GetOidForPath Docs

### ISSUE THREAD

**Issue by dborncamp** [greymatter-io/nifi-sdk#14]
Several of the fields have been updated to support expression language but those changes are not reflected in the documentation https://github.com/greymatter-io/nifi-sdk/blob/main/doc/GetOidForPath.md and should be updated. Also, add documentation about `USER_DN` field.

**Comment by TheMover** [comment]
`USER_DN` is a dynamic property and does not necessarily HAVE to be USER_DN, any key/value pair will be accepted by the processor and sent as headers. This is already in the document so I don't think the specific header needs to be.

**Comment by dborncamp** [comment]
I don't see USER_DN documented in https://github.com/greymatter-io/nifi-sdk/blob/main/doc/GetOidForPath.md . Is it under a different value?

**Comment by dborncamp** [comment]
Closed by #15
