### ISSUE TITLE
Investigate dynamic properties in processors to make sure they are evaluating expression language correctly

### ISSUE THREAD

**Issue by TheMover** [greymatter-io/nifi-sdk#27]

**Comment by TheMover** [comment]
The annotation for dynamic properties in both ListFiles and GetOidForPath state that dynamic properties are evaluated using expression language, however the implementation of the code that actually pulls the dynamic property value is missing the validator for evaluating expression language, even though it has the expression language in it's scope. It's interesting that nifi allows this discrepancy but this is likely the issue that is causing the ELS value not to be evaluated for dynamic properties like "USER_DN"

**Comment by dborncamp** [comment]
@TheMover Was this closed by #30  and #31?
