### ISSUE TITLE
Error using processors with Nifi 1.12.0 - Possible refactoring needed

### ISSUE THREAD

**Issue by lucasmoten** [greymatter-io/nifi-sdk#33]
Captured from issue reported in slack

> So I reverted to an older version of nifi and that solved the pathing issue. Now I’m getting regular SSLHandshake errors, which I’m guessing is due to my actual certification configuration.
> ...
> anyone know why I might be getting into this error when running the GetOidForPath processor:
> ```
> java.lang.NoClassDefFoundError: org/apache/nifi/ssl/SSLContextService$ClientAuth
>     at > com.deciphernow.greymatter.data.nifi.properties.CommonProperties.$anonfun$parseSSLContext$2(CommonProperties.scala:40)
> ```
> The import statement in CommonProperties is: import org.apache.nifi.ssl.SSLContextService.ClientAuth
> I looked at the docs for nifi 1.12.0 and it looks like ClientAuth is under the SSLContextFactory class, not SSLContextService. Were these processors built under an earlier version of nifi perhaps?

**Comment by lucasmoten** [comment]
Release Notes for Apache NiFi 1.12.0 are here
https://cwiki.apache.org/confluence/display/NIFI/Release+Notes#ReleaseNotes-Version1.12.0

Version 1.12.0
Version 1.12.0 of Apache NiFi is a feature, stability, and security related release

Release Date: August 18, 2020

Highlights of the 1.12.0 release include:

- By very popular demand you can now empty all queues in a given process group with a single request!
- New processor to write scripted record transforms live in the flow
- Expose a REST Endpoint for easy metric scraping by Prometheus
- Ability to specify group level flow file concurrency - for instance run a single flow file end to end before running another for  traditional job handling
- Improved several capabilities related to Azure service interaction
- Improved AMQP and MQTT support as well as JMS improvements
- Support for latest Kafka 2.6 clients

A full list of issues that were resolved can be found at: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12316020&version=12346778

----

As of writing this comment, there is a newer version 1.12.1 that was released 2020-09-28.

**Comment by dborncamp** [comment]
Not going to be as easy as I had hoped. NiFi 1.12.1 bans `org.json:json` https://github.com/apache/nifi/blob/rel/nifi-1.12.1/pom.xml#L628 which we use. Refactor will be needed.

**Comment by dborncamp** [comment]
Looking a little deeper, I think this is going to take several days of effort, but probably less than a week. The `org.json` library was buried deep into the `BuildPermissions` and `GetPolicies` processors as well as their tests.

**Comment by dborncamp** [comment]
Looks like the latest release is 1.12.1. I am going to dev against that since we want it to be the most current.
