### ISSUE TITLE
Fix GetPolicies to map response to attributes as JSON

### ISSUE THREAD

**Issue by lucasmoten** [greymatter-io/nifi-sdk#47]
1. Currently, the GetPolicies processor is able to set flow file attributes.  Not all attributes are listed below, but the relevant ones are as follows.  Note that "acm" and "permission" inputs are proper JSON, but the values set for "gmdata.objectpolicy" and "gmdata.security" are not JSON as they don't quote the fields names and values.

```
acm
  { "version":"2.1.0", "classif":"U" }
getpolicies.remote.dn
  CN=*.greymatter.devcloud.di2e.net,O=DI2E,L=Chantilly,ST=Virginia,C=US
getpolicies.request.url
  https://windstalker.greymatter.devcloud.di2e.net/services/acm-server/latest/convert/addpermissions
getpolicies.response.body
  Empty string set
getpolicies.status.code
  200
getpolicies.status.message
  OK
getpolicies.tx.id
  7f146c19-9e29-4952-8a03-7da03fc47363
gmdata.lisp
  (if (and (and (contains f_clearance u))) (if (tells userDN) (or) (yield R)))
gmdata.objectpolicy
  {label=ACM-DATA-POLICY-GENERATED, requirements={f=if, a=[{f=and, a=[{f=and, a=[{f=contains, a=[{v=f_clearance}, {v=u}]}]}]}, {f=if, a=[{f=tells, a=[{v=userDN}]}, {f=or}, {f=yield, a=[{v=R}]}]}]}}
gmdata.originalobjectpolicy
  "{acm={classif=U, portion=U, banner=UNCLASSIFIED, version=2.1.0, dissem_countries=[USA], share={}, f_clearance=[u]}, permission={create={}, read={}, update={}, delete={}, execute={}, purge={}}}"
gmdata.parentoid
  1650ad5108190bfd
gmdata.security
  {label=UNCLASSIFIED, foreground=#FFFFFF, background=007A33}
permission
  { "create" : { "allow" : [ "nifi" ] }, "read" : { "allow" : [ "group/_everyone", "nifi" ] }, "update" : { "allow" : [ "nifi" ] }, "delete" : { "allow" : [ "nifi" ] } }
```

One of these is true
* GetPolicies is taking a valid response from ACM Data Policy service and writing incorrect attributes as a strings
* ACM Data Policy is returning strings instead of JSON

This is causing errors further in processing flow that depends on this

**Comment by dborncamp** [comment]
The GetPolicies processor makes it a string https://github.com/greymatter-io/nifi-sdk/blob/main/gmd-sdk/nifi-data-processors/src/main/scala/com/deciphernow/greymatter/data/nifi/processors/GetPolicies.java#L379-L383

**Comment by lucasmoten** [comment]
From Seth
> With Jackson  you’ll need to use the mapper.mapValueToString($someobject) to get a json string representation - where mapper is an ObjectMapper
