### ISSUE TITLE
Add Processor to GetFileProperties given a file path

### ISSUE THREAD

**Issue by lucasmoten** [greymatter-io/nifi-sdk#53]
For some flows, this is helpful to determine if a file is already present in Grey Matter Data.  Checked up front from a list of files being transferred, this would allow for avoiding retrieving the file stream from source location, and sending to GM Data, resulting in a speedup in running flows multiple times, reduced network bandwidth, and a means for rationally handling watching a source location for changes

As with other processors that communicate with Grey Matter Data, it should support a Remote URL, potential SSL security context, Attributes to Send (for USER_DN).

We will need to compose the target filename and path from source and check that using this processor.

Response from this processor can have the file size and sha256plain and those can optionally be checked against the source.

**Comment by dborncamp** [comment]
Closed with #54
